config/routes.rb
Rails.application.routes.draw do
  
  resources :champion
  root 'static_pages#home'
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
 
  get 'champion/:id'              => 'champion#show'
  get 'champion/condensed/:id'    => 'champion#showCondensed'
  get 'champion'                  => 'champion#index'
  
  

end

app/models/champion.rb
class Champion < ActiveJSON::Base
  set_root_path Rails.root.join('app', 'models', 'data')
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/champion_controller.rb
class ChampionController < ApplicationController
  
  def index
    @champions = Champion.all.sort { |x,y| x.id <=> y.id}
  end
  
  def show
    @champion = Champion.find params[:id]
  end
  
  def showCondensed
    @champion = Champion.find params[:id];
    render :json => @champion
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "LoL Ref"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/champion_helper.rb
module ChampionHelper
end

app/views/champion/index.html.erb
<% provide(:title, "Champion Index") %>
<h1>Champion Index</h1>

<div id="champion-details-template"></div>
<table id="champion-table" class="table table-hover">
  <thead>
    <tr>
	  <th>#</th>
      <th>Name</th>
	  <th>Title</th>
    </tr>
  </thead>

<% @champions.each do |champion| %>
  <tr id="<%= champion.id %>">
    <td><%= champion.id %></td>
    <td><%= champion.name %></td>
    <td><%= champion.title %></td>
  </tr>
<% end %>
</table>

<script type="text/javascript">
$("#champion-table > tbody > tr").click(
	function(){
		$.getJSON( "/champion/condensed/"+$(this).attr('id'), function(data){
			mine = $("champion-details-template").clone();
			mine.attr("id", "#champion-details-"+data.attributes.id);
			//build clone
			mine.html = data.attributes.name;
			mine.insertAfter($("champion-details-template"));
			//clone.toggleClass("hidden");
		});
	});
</script>

app/views/champion/show.html.erb
<% provide(:title, @champion.name ) %>
<h1><%= @champion.name %> <%= @champion.title %></h1>

<!--default skin image -->

<h3>Abilities</h3>
<table id="champion-table" class="table table-striped">
  <thead>
  </thead>
  <tr>
    <td>Passive</td>
    <td>image</td>
    <td>ability text</td>
	<td>id</td>
  </tr>
  <tr>
    <td>Q</td>
    <td>image</td>
    <td>ability text</td>
	<td>id</td>
  </tr>
  <tr>
    <td>W</td>
    <td>image</td>
    <td>ability text</td>
	<td>id</td>
  </tr>
  <tr>
    <td>E</td>
    <td>image</td>
    <td>ability text</td>
	<td>id</td>
  </tr>
  <tr>
    <td>R</td>
    <td>image</td>
    <td>ability text</td>
	<td>id</td>
  </tr>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The lol reference application
    by <a href="http://www.danonrockstar.com/">Dan Kirschner</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact Me", contact_path %></li>
      <li><a href="http://www.danonrockstar.com/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
        <%= link_to "LoL REF", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<%= favicon_link_tag 'favicon.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
	  <%= render 'layouts/footer' %>
    </div>
  </body>
  <%= debug(params) if Rails.env.development? %>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  TBD
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact Me") %>
<h1>Contact Me</h1>
<p>
  Feel free to send any feedback you have by contacting me at DPKirschner@gmail.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help with this site by <%= link_to "contacting me", contact_path %> directly. If you are technically inclined you could also head to <a href="https://github.com/dpkirschner/lolref"> github </a> and debug the issue directly.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to LoL Reference</h1>
	<h2>
  	  This should give you all the base data you need to start showing cool data!
	</h2>

  	<%= link_to "show me the champs!", champion_index_path, class: "btn btn-lg btn-primary" %>
</div>